package mesh

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const beginSSHConfig = "# ai-mesh:ssh:begin"
const endSSHConfig = "# ai-mesh:ssh:end"

// SSHConfig repairs client aliases for an existing installation without
// enrolling computers, changing incoming access, or contacting any peer.
func (s *Store) SSHConfig() error {
	return withLock(s.path("config.lock"), func() error {
		c, err := s.Config()
		if err != nil {
			return err
		}
		return s.writeSSHConfig(c)
	})
}

func withoutSSHConfig(existing string) (string, error) {
	start, end := -1, -1
	offset := 0
	for _, line := range strings.SplitAfter(existing, "\n") {
		switch strings.TrimSpace(line) {
		case beginSSHConfig:
			if start >= 0 || end >= 0 {
				return "", fmt.Errorf("malformed Mesh SSH block; existing SSH configuration was not changed")
			}
			start = offset
		case endSSHConfig:
			if start < 0 || end >= 0 {
				return "", fmt.Errorf("malformed Mesh SSH block; existing SSH configuration was not changed")
			}
			end = offset + len(line)
		}
		offset += len(line)
	}
	if start < 0 {
		return existing, nil
	}
	if end < 0 {
		return "", fmt.Errorf("malformed Mesh SSH block; existing SSH configuration was not changed")
	}
	return existing[:start] + existing[end:], nil
}

func sshConfigQuote(value string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value) + `"`
}

func (s *Store) sshClientConfig(c Config, existing string) (string, error) {
	rest, err := withoutSSHConfig(existing)
	if err != nil {
		return "", err
	}
	for _, path := range []string{s.Root, s.UserHome} {
		if strings.ContainsAny(path, "\r\n\x00") || strings.Contains(path, "${") {
			return "", fmt.Errorf("invalid path for Mesh SSH configuration")
		}
	}
	// OpenSSH expands percent tokens in IdentityFile and UserKnownHostsFile.
	path := func(value string) string { return sshConfigQuote(strings.ReplaceAll(value, "%", "%%")) }
	var peers []Peer
	for _, p := range c.Peers {
		if p.Incoming {
			peers = append(peers, p)
		}
	}
	if len(peers) == 0 {
		return rest, nil
	}
	sort.Slice(peers, func(i, j int) bool { return peers[i].Name < peers[j].Name })
	var block strings.Builder
	fmt.Fprintln(&block, beginSSHConfig)
	fmt.Fprintln(&block, "# Generated by Mesh. Update with: mesh ssh-config")
	for _, p := range peers {
		if !validID.MatchString(p.Name) {
			return "", fmt.Errorf("invalid machine name for SSH alias")
		}
		if err := validateEndpoint(p.Endpoint); err != nil {
			return "", err
		}
		if strings.ContainsAny(p.Endpoint.Host+p.Endpoint.User, "\x00%") {
			return "", fmt.Errorf("invalid SSH alias endpoint")
		}
		fmt.Fprintf(&block, "Host %s\n", p.Name)
		// Enrollment also accepts an existing SSH alias. If its name matches
		// the Mesh name, retain its original HostName mapping instead of
		// replacing that mapping with the alias itself.
		if !strings.EqualFold(p.Endpoint.Host, p.Name) {
			fmt.Fprintf(&block, "  HostName %s\n", sshConfigQuote(p.Endpoint.Host))
		}
		fmt.Fprintf(&block, "  User %s\n  Port %d\n", sshConfigQuote(p.Endpoint.User), p.Endpoint.Port)
		fmt.Fprintf(&block, "  IdentityFile %s\n  IdentitiesOnly yes\n", path(s.path("keys", "id_ed25519")))
		fmt.Fprintf(&block, "  UserKnownHostsFile %s %s\n", path(s.path("known_hosts")), path(filepath.Join(s.UserHome, ".ssh", "known_hosts")))
		fmt.Fprintln(&block, "  StrictHostKeyChecking yes\n  ForwardAgent no\n  ConnectTimeout 8\n  ServerAliveInterval 15\n  ServerAliveCountMax 3")
	}
	// OpenSSH uses the first value it reads. Prepend aliases before Host *
	// defaults, then restore the global scope for the original configuration.
	fmt.Fprintln(&block, "Host *")
	fmt.Fprintln(&block, endSSHConfig)
	return block.String() + rest, nil
}

func (s *Store) writeSSHConfig(c Config) error {
	file := filepath.Join(s.UserHome, ".ssh", "config")
	if info, err := os.Lstat(file); err == nil && info.Mode()&os.ModeSymlink != 0 {
		resolved, err := filepath.EvalSymlinks(file)
		if err != nil {
			return err
		}
		file = resolved
	}
	return withLock(file+".mesh.lock", func() error {
		old, err := os.ReadFile(file)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		updated, err := s.sshClientConfig(c, string(old))
		if err != nil {
			return err
		}
		if updated == string(old) {
			return nil
		}
		if len(old) > 0 {
			if _, err := os.Stat(file + ".pre-mesh"); os.IsNotExist(err) {
				if err := atomicWrite(file+".pre-mesh", old, 0600); err != nil {
					return err
				}
			}
		}
		return atomicWrite(file, []byte(updated), 0600)
	})
}
